[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["Tadeo Kondrak <me@tadeo.ca>"]
edition = "2018"
publish = false

[[bin]]
name = "01"
path = "01.rs"

[[bin]]
name = "02"
path = "02.rs"

[[bin]]
name = "03"
path = "03.rs"

[[bin]]
name = "04"
path = "04.rs"
