[package]
name = "advent-of-code-2022"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Tadeo Kondrak <me@tadeo.ca>"]

[dependencies]

[[bin]]
name = "01"
path = "01.rs"

[[bin]]
name = "02"
path = "02.rs"

[[bin]]
name = "03"
path = "03.rs"

[[bin]]
name = "04"
path = "04.rs"
